"""empty message

Revision ID: dce8fa9f5dad
Revises: d16e43439468
Create Date: 2018-11-19 19:20:23.689007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce8fa9f5dad'
down_revision = 'd16e43439468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('syx_file', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('flow_input')
    op.drop_table('flow')
    op.drop_table('flow_output')
    op.add_column('job', sa.Column('analysis_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'analysis', ['analysis_id'], ['id'])
    op.drop_column('job', 'flow_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('flow_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'flow', ['flow_id'], ['id'])
    op.drop_column('job', 'analysis_id')
    op.create_table('flow_output',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=64), nullable=True),
    sa.Column('type', sa.VARCHAR(length=16), nullable=True),
    sa.Column('flow_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=64), nullable=True),
    sa.Column('syx_file', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_input',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=64), nullable=True),
    sa.Column('type', sa.VARCHAR(length=16), nullable=True),
    sa.Column('flow_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('analysis_output')
    op.drop_table('analysis_input')
    op.drop_table('analysis')
    # ### end Alembic commands ###
